In [1]:
import torch

### **Tensor Basics**

Empty Tensor

In [14]:
x=torch.empty(2)
y=torch.empty(2,3)
z=torch.empty(2,2,3)
x,y,z

(tensor([0., 0.]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[[-4.8282e+29,  2.0823e-42,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],
 
         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]))

Random,Zeros,Ones Tensor (Most Like Numpy)

In [16]:
random_tensor=torch.rand(2,2)
ones_tensor=torch.ones(2,2)
zeros_tensor=torch.zeros(2,2)

random_tensor,ones_tensor,zeros_tensor

(tensor([[0.2880, 0.9460],
         [0.0014, 0.0087]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [17]:
random_tensor.dtype

torch.float32